@startuml
!theme sketchy
skinparam defaultFontName Calibri
skinparam handwritten true
skinparam backgroundColor white
skinparam DefaultFontColor white
skinparam shadowing true
skinparam ArrowFontColor black
skinparam ArrowFontSize 20
skinparam TitleFontColor black
title Protoss vs Terran scouting flowchart (version 0.8)
start
:Send initial scouting Probe (after 16 Gateway);
if (Is there a Barracks in the Terran's Base?) then (yes)
    if (Is the base already walled off) then (yes)
        :Get an early Shield Battery at your natural
        and keep scouting his natural so you can see
        when units are moving out or he expands.;
        note left
            Getting the Shield Battery early
            will not make you fall behind, in
            case he just expands.
            He invested money into a fast
            2nd Depot which delays his CC.
        end note
        :Send a Probe from your main to scout for proxies.;
    else (no)
        if (How many Gas do you see?) then (1 or less Gas)
            :Continue with normal build;
            note left
                Keep in mind, that he can still
                add or proxy additional Barracks
                and for example play proxy
                Marauder or Marines.

                In that case, there is no consistent
                way of scouting it and your build order
                and micro have to make up for it.
            end note
        else (2 Gas)
            :You play vs. some kind of one base aggression.
            Potentially proxy Factory or proxy Reaper but 
            might aswell be a 1/1/1.;
        endif
    endif
else (no)
    if (Is the Terran base fully walled off with Depots?) then (yes)
        :This is highly inefficient from the Terran but you are definetily getting cheesed.;
    else (no)
        if (Is there any gas taken?) then (yes)
            :You play vs. some kind of Gas based proxy (Reaper, Marauder, Factory).;
        else (no)
            :You play vs. proxy rax marines.;
        endif
    endif
endif
if (Have you confirmed a proxy or one base play?) then (yes)
    if (Is it Proxy Rax Marines?) then (yes)
        :Defend like this:
        - Chronoboost Zealot
        - 2nd Gateway
        - 1-2 Shield Batteries in main base
        - Chronoboost Stalkers non stop
        - do not expand until you defended;
        note left
            This includes
            Marines, SCVs
            and Bunkers 
            at ~2:30
        end note
    else (no)
        :Go Core first and expand but get a Shield Battery at your natural and
        check with a probe from your main if you can find the proxy or enemy
        units walking around.;
        note right
            You can find out what you are up against by picking up
            on some clues:
            - Tech Lab on proxied Rax -> 2 Rax Marauder
            - no Tech Lab on proxied Rax -> 3 Rax Reaper

            Clues that may lead to a proxy Factory or 1/1/1 are:
            - proxied Factory
            - no attack by ~2:45 (besides a single reaper)
            - Rax not producing units
            - 2 Gas (Reapers also use 2 Gas)

            Keep in mind, that Terran can also combine Factory
            with Bio units, for example proxy Marauder into
            proxy Factory -> Marauder Cyclone
        end note
        switch (Which one?)
        case (Proxy or regular Factory)
            :Defend like this:
            - 3 Gates
            - Robo, Stargate or Twilight
            - 2 Base
            - 1 Shield Battery at natural
            - cut probes at 1,5 base saturation

            I suggest 3 Gate Phoenix as this seems to deal quite
            well with anything from 1 base factory / starport.;
            note left
                I am not exactly sure what to do in this case and
                the explained response here is just a suggestion
                that worked for me quite well in the past.

                Keep in mind that its hard to determine what Terran
                will do exactly but the most common builds will hit at:
                - Marine Tank Liberator (~?:??)
                - Reactor Cyclone (~3:15)
                - Marauder Cyclone (~?:??)
                - Widow Mine or Hellion Drop (~4:00)
            end note
        case (2 Rax Marauder)
            :First Marauder hits at ~2:30

            Defend like this:
            - 2 Gates
            - 2 Base (but no Probes for 2nd Nexus)
            - cut Probes at 1 base saturation
            - 2 Shield Batteries;
        case (3 Rax Reaper)
            :First Reaper hits at ~2:30

            Defend like this:
            - 1 Shield Battery in each mineral line
            - 2 Gates
            - cut Probes at 1 base saturation;
        endswitch
    endif
else (no)
    :Shade forward first Adept to scout;
    if (Is there a second Command Center?) then (yes)
        :Continue with normal build;
    else (no)
        repeat
            :Stay with Adept in front of Natural to figure out what he is doing;
            if (Are there units walking out of his base?) then (yes)
                if (Is it Hellions?) then (yes)
                    :Wall of your natural;
                else (no)
                    :Get units and a Shield Battery at your natural;
                endif
            else (no)
            endif
        repeat while (Repeat until units walk out or you have enough informations)
    endif
endif
:Send any "air" scout your build allows (Hallucinated Pheonix, Observer or Stargate unit);
if (Is he still on one base?) then (yes)
    if (Is he only having Barracks?) then (yes)
        :You play vs. 3 Rax (Marines / Marauder with Stim)
        Defend like this:
        - cut probe production (approximately 1 - 1,5 base saturaion)
        - add 2-4 Shield Batteries on natural
        - 3 Gateways
        - build as many Units as you can;
    else (no)
        :You play vs. 1/1/1 (possibly Marines, Mines, Tanks, Banshees, Cyclones)
        Defend like this:
        - cut probe production (approximately 1,5 base saturation)
        - 3-5 Gateways (depending on Probe count)
        - tech building (Robo, Stargate, Twilight)
        - something vs. cloak Banshees (Observer, Oracle, Cannon)
        - build as many units as you can (not too many Shield Batteries as they wont help vs. Tanks);
    endif
    :After defending you can continue your normal build.
    You should be really ahead now and may be able to counterattack.;
else (no)
    :Check whether he plays Bio or Mech;
    note right
        Bio / Mech decision cheat sheet
        Usually Mech play can be identified just by
        the missing Bio Indications as Terrans want to
        get their Bio upgrades early on (Stim, Combat Shield, etc.)

        The following Indications suggest Bio play:
        - Marines with Combat Shields
        - multiple Barracks
        - researching Tech Lab (on Barracks)
        - multiple Engineering Bays
        - Marauders

        The following Indications suggest Mech play:
        - multiple Factories
        - Hellions
        - lack of Bio Units
        - early Armory
        - researching Tech Lab (on Factory)
        - early 4th Gas
    end note
    if (Is he playing Bio or Mech?) then (Bio)
        :Check what are you playing against;
        note left
            There are a couple of different Bio openers a Terran can do.
            I will try to cover the most popular ones.
        end note
        switch (What are you seeing?)
        case (1/1/1)
            if (Do you see a fusion core?) then (yes)
                :You are facing a Battle Cruiser opening.
                A Battle Cruiser will warpin in one of your mineral lines at ~5:30.
                
                Defend like this:
                - 1 Shield Battery in every mineral line
                - 5 Stalkers in every mineral line;
            else (no)
                :You are probably facing a Widow Mine drop or cloaked Banshees.
                Either one will hit your base at ~4:30

                Defend like this:
                - 3-4 Stalkers or Phoenix in position (Phoenix only if you opened Stargate)
                - Have detection ready (Observer, Cannon or Oracle)
                - If you confirmed its Banshee, you can add a Shield Battery in each mineral line;
            endif
            :Keep in mind, that 1/1/1 builds are greedy tech builds that are not aiming to kill you,
            but to keep you at home. The Terran can prepare a follow up push or a relatively fast 3rd CC 
            behind the 1/1/1 harass.

            You need to continously scout after the harass to figure out what happens next.;
        case (3 Rax)
            :You are facing Bio aggression.
            With a 3 Rax build the Terran delays tech to get Bio upgrades and
            Bio units quickly. This will almost always result in some kind of
            Bio aggression with upgrades (Stim, Combat Shields, Concusive Shells).

            What exactly the Terran will do is hard to tell and will require
            constant scouting. If he adds Marauders, he will research Concusive Shells.
            If you are playing Blink Stalkers you would normally try and pressure with them to
            delay the attack. Because of Concusive Shells you should absolutely avoid that in this case.

            The exact timing of his attack may vary depending on his exact build but
            you can roughly expect the attack to come between ~5:00 if only with Marines and ~7:00 if they waited for Medivacs.

            Depending on your build you can be quite greedy and get away with it. For example with an early 3rd Base
            but you will need to scout constantly to see when he moves out.

            To defend this, you need to have enough units, Shield Batteries and Force Fields ready.;
        case (2 Barracks, 1 Factory, 1 Starport and a bunch of marines)
            :You are facing a 16 Marine Stim drop.
            This is a timing with 16 Stim Marines and 2 Medivacs.
            It will hit your base at ~5:00.
            
            Find out where he will strike and have units in position.
            This attack can be quite potent if he catches you offguard 
            but is easily deflected if you are in position.;
        case (Fast 3rd Command Center)
            :You are facing a very fast 3rd CC and this means
            that you are not in immediate danger but will fall
            behind if you do not react.

            Your options are one of the following:
            - be greedy urself (fast 3rd and tech / upgrades)
            - get 8-10 gateways and allin;
        endswitch
    else (Mech)
        :Todo;
        note right
            Unfortunately I do not know how to identify Mech playstyles all that well
            but usually you just want to play Chargelot Archon and add Immortals when they add Thor's.
            You might want to adapt against some uniqle playstyles like mass Banshee or mass Battle Cruiser
            but in general, this will deal pretty well with anything.
            
            Keep in mind that against Cyclone Hellion you want to add 2-3 Colossus or Storm.
        end note
    endif
endif
stop
@enduml